drivers: touchscreen: xiaomi_touch: Set missing functions prototypes
../../../../../../kernel/xiaomi/sm8450/drivers/input/touchscreen/xiaomi/xiaomi_touch.c:211:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct class *get_xiaomi_touch_class()
                                    ^
                                     void
../../../../../../kernel/xiaomi/sm8450/drivers/input/touchscreen/xiaomi/xiaomi_touch.c:217:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *get_xiaomi_touch_dev()
                                   ^
                                    void
../../../../../../kernel/xiaomi/sm8450/drivers/input/touchscreen/xiaomi/xiaomi_touch.c:537:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int update_touch_rawdata()
                        ^
                         void

Change-Id: I10e58c7f7d067a467e91f944783dcb1121d2a156