drivers: touchscreen: fts_spi: Set missing functions prototypes
../../../../../../kernel/xiaomi/sm8450/drivers/input/touchscreen/fts_spi/fts_lib/ftsIO.c:102:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void
../../../../../../kernel/xiaomi/sm8450/drivers/input/touchscreen/fts_spi/fts_lib/ftsIO.c:127:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void

Change-Id: I7495f71dd263d8df25acdca2afcb7ea3ed3dec11